let lessons = [
  {
    id: 1001,
    programme: "Coding",
    location: "Palm Jumeirah",
    price: 500,
    spaces: 5,
    image: "img/coding.jpg",
  },
  {
    id: 1002,
    programme: "Robotics",
    location: "Dubai Museum",
    price: 300,
    spaces: 5,
    image: "img/robotics.jpg",
  },
  {
    id: 1003,
    programme: "Mathematics",
    location: "Burj Al Arab",
    price: 200,
    spaces: 5,
    image: "img/mathematics.jpg",
  },
  {
    id: 1004,
    programme: "Science",
    location: "Deira",
    price: 250,
    spaces: 5,
    image: "img/science.jpg",
  },
  {
    id: 1005,
    programme: "Art",
    location: "Al Fahidi",
    price: 150,
    spaces: 5,
    image: "img/art.jpg",
  },
  {
    id: 1006,
    programme: "Literature",
    location: "Mirdif",
    price: 600,
    spaces: 5,
    image: "img/literature.jpg",
  },
  {
    id: 1007,
    programme: "Debate",
    location: "The Greens",
    price: 100,
    spaces: 5,
    image: "img/debate.jpg",
  },
  {
    id: 1008,
    programme: "Environmental",
    location: "Dubai Mall",
    price: 650,
    spaces: 5,
    image: "img/environmental.jpg",
  },
  {
    id: 1009,
    programme: "Fitness",
    location: "Burj Khalifa",
    price: 1000,
    spaces: 5,
    image: "img/fitness.jpg",
  },
  {
    id: 1006,
    programme: "Language",
    location: "Al Barsha",
    price: 800,
    spaces: 5,
    image: "img/language.jpg",
  },
];
